// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN55qyHECC1JYr-qh8DlFYdgSoXkhcHyw',
    appId: '1:591139904486:web:fd8f93d066412158765427',
    messagingSenderId: '591139904486',
    projectId: 'didasnotes',
    authDomain: 'didasnotes.firebaseapp.com',
    storageBucket: 'didasnotes.appspot.com',
    measurementId: 'G-8WMBER624V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy5opx_fY67icEnw7e1yln1LHodDFKKz4',
    appId: '1:591139904486:android:93a6d8bb19c53d1b765427',
    messagingSenderId: '591139904486',
    projectId: 'didasnotes',
    storageBucket: 'didasnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp9uPbHEz5p5drtcWM9YihKg3znbb_zsg',
    appId: '1:591139904486:ios:2a71d4868151e423765427',
    messagingSenderId: '591139904486',
    projectId: 'didasnotes',
    storageBucket: 'didasnotes.appspot.com',
    iosClientId: '591139904486-ge6qsnt71bumo4a6arrkg83v8678fanv.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuffup.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp9uPbHEz5p5drtcWM9YihKg3znbb_zsg',
    appId: '1:591139904486:ios:6dfcb3337511b5e2765427',
    messagingSenderId: '591139904486',
    projectId: 'didasnotes',
    storageBucket: 'didasnotes.appspot.com',
    iosClientId: '591139904486-jnt12bhmphqind39on5o50uq3e95jqo0.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuffup.mynotes.RunnerTests',
  );
}
